<?php
$baseUrl='/mochila';
?>


<meta charset="utf-8">
<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

<link href="datepicker/css/bootstrap-formhelpers.min.css" rel="stylesheet" media="screen">
<link href="tokenfield/assets/tokenfield-typeahead.css" rel="stylesheet" type="text/css">
<link href="tokenfield/bootstrap-tokenfield/bootstrap-tokenfield.css" rel="stylesheet" type="text/css">
<link href="select2-3.4.5/select2.css" rel="stylesheet" type="text/css">
<link href="select2-3.4.5/select2-bootstrap.css" rel="stylesheet" type="text/css">

<link href="css/navbar.css" rel="stylesheet" type="text/css">
<link href="css/dagrlist.css" rel="stylesheet" type="text/css">
<link href="css/popover.css" rel="stylesheet" type="text/css">

<script type="text/javascript" src="js/jquery-2.0.3.js"></script>
<script type="text/javascript" src="tokenfield/bootstrap-tokenfield/bootstrap-tokenfield.min.js"></script>
<script type="text/javascript" src="tokenfield/assets/typeahead.min.js"></script>
<script type="text/javascript" src="select2-3.4.5/select2.js"></script>
<script type="text/javascript" src="js/mustache.js/mustache.js"></script>

 

<script type="text/javascript" src="js/mochila.js"></script>
<script type="text/javascript" src="js/navbar.js"></script>
<script type="text/javascript" src="js/tags.js"></script>




