<?php
$baseUrl='/mochila';
?>


<meta charset="utf-8">
<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css">

<link href="datepicker/css/bootstrap-formhelpers.min.css" rel="stylesheet" media="screen">

<link href="css/navbar.css" rel="stylesheet" type="text/css">
<link href="css/dagrlist.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript" src="js/navbar.js"></script>



      
